spring:
  datasource:
    url: jdbc:h2:~/inventivDB;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  config:
    activate:
      on-profile: test
